server:
  port: 7788

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 

  jpa:
    database-platform: 
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        
logging:
  level:
    org:
      hibernate: info
      springframework:
        security: debug